name: secretbin
services:
  postgres:
    image: postgres:17
    container_name: postgres
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    environment:
      POSTGRES_DATABASE: secretbin
      POSTGRES_USER: secretbin
      POSTGRES_PASSWORD: abc123
      TZ: Europe/Berlin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./certs/server.crt:/var/lib/postgresql/server.crt
      - ./certs/server.key:/var/lib/postgresql/server.key
    networks:
      - secretbin

  secretbin:
    image: ghcr.io/nihility-io/secretbin:dev
    container_name: secretbin
    entrypoint: ["deno", "run", "--cert", "certs/ca.crt", "-A", "main.ts"]
    read_only: true
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ../config.yaml
        target: /app/config.yaml
      - type: bind
        source: ./config.db.yaml
        target: /app/config.db.yaml
      - type: bind
        source: ./certs
        target: /app/certs
    networks:
      - secretbin

volumes:
  postgres-data:

networks:
  secretbin:
