# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"



vars:
  IMAGE: "ghcr.io/nihility-io/secretbin"
  VERSION:
    sh: jq -r '.version' < deno.json
  PWD:
    sh: pwd
  DENO_VERSION:
    sh: deno -v | awk '{print $2}'

tasks:
  default:
    - task: "build"
  build:
    desc: Builds the container image
    cmd: |
      docker build --no-cache \
        --build-arg DENO_VERSION={{.DENO_VERSION}} \
        --file container/Containerfile \
        --tag {{.IMAGE}}:{{.VERSION}} .
  run:
    desc: Runs the container locally
    cmd: |
      docker run --rm --interactive --tty \
        --network=secretbin_network \
        --read-only \
        --mount type=bind,src="{{.PWD}}/config.yaml",target=/app/config.yaml \
        --mount type=bind,src="{{.PWD}}/config.db.yaml",target=/app/config.db.yaml \
        --publish 8000:8000 \
        --name secretbin {{.IMAGE}}:{{.VERSION}}
  publish:
    desc: Builds and publishes the container image
    cmd: |
      docker buildx build --no-cache \
        --build-arg DENO_VERSION={{.DENO_VERSION}} \
        --file container/Containerfile \
        --platform linux/amd64,linux/arm64 \
        --tag {{.IMAGE}}:{{.VERSION}} \
        --tag {{.IMAGE}}:dev \
        --annotation "index:org.opencontainers.image.title=SecretBin" \
        --annotation "index:org.opencontainers.image.authors=Nihility.io" \
        --annotation "index:org.opencontainers.image.documentation=https://github.com/Nihility-io/SecretBin" \
        --annotation "index:org.opencontainers.image.source=https://github.com/Nihility-io/SecretBin" \
        --annotation "index:org.opencontainers.image.licenses=MIT" \
        --annotation "index:org.opencontainers.image.description=SecretBin is a web app for sharing secrets like tokens and passwords." \
        --push .