services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DATABASE: secretbin
      POSTGRES_USER: secretbin
      POSTGRES_PASSWORD: abc123
      TZ: Europe/Berlin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: secretbin@nihility.io
      PGADMIN_DEFAULT_PASSWORD: abc123
    ports:
      - "15432:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  network:
